import { Contact } from "src/app/core/interfaces/contacts";

export const contactosFalsos: Contact[] = [{
    "name": "Marsh",
    "lastname": "Ramirez",
    "celularNumber": "49-144-2292"
  }, {
    "name": "Farlee",
    "lastname": "Deveril",
    "celularNumber": "12-209-4481"
  }, {
    "name": "Frederica",
    "lastname": "Spraggon",
    "celularNumber": "75-849-5931"
  }, {
    "name": "Claudia",
    "lastname": "Feldon",
    "celularNumber": "55-037-0273"
  }, {
    "name": "Eilis",
    "lastname": "Coolican",
    "celularNumber": "39-365-7035"
  }, {
    "name": "Staci",
    "lastname": "Berge",
    "celularNumber": "87-832-1828"
  }, {
    "name": "Nelli",
    "lastname": "Sansbury",
    "celularNumber": "31-604-1173"
  }, {
    "name": "Amii",
    "lastname": "Woodrow",
    "celularNumber": "98-672-6847"
  }, {
    "name": "Garth",
    "lastname": "Malam",
    "celularNumber": "73-976-0236"
  }, {
    "name": "Mireille",
    "lastname": "Wyley",
    "celularNumber": "16-238-1007"
  }, {
    "name": "Gleda",
    "lastname": "Gildersleeve",
    "celularNumber": "80-497-3431"
  }, {
    "name": "Khalil",
    "lastname": "Fedoronko",
    "celularNumber": "49-713-1005"
  }, {
    "name": "West",
    "lastname": "Whistance",
    "celularNumber": "97-727-8564"
  }, {
    "name": "Menard",
    "lastname": "Stealfox",
    "celularNumber": "20-697-7153"
  }, {
    "name": "Orren",
    "lastname": "Bonevant",
    "celularNumber": "53-459-5466"
  }, {
    "name": "Rafaela",
    "lastname": "Sand",
    "celularNumber": "42-482-1358"
  }, {
    "name": "Thebault",
    "lastname": "Murdoch",
    "celularNumber": "54-164-9942"
  }, {
    "name": "Johann",
    "lastname": "Dewsbury",
    "celularNumber": "60-897-5879"
  }, {
    "name": "Kalle",
    "lastname": "Rappaport",
    "celularNumber": "52-568-9137"
  }, {
    "name": "Putnam",
    "lastname": "Rosendale",
    "celularNumber": "77-397-5617"
  }]
  